### ISSUE TITLE
Flavor without GMS

### ISSUE THREAD

**Issue by dalb8** [VersoBit/WeatherDoge#5]
It's nice that the app works without Google Play location services, but the Google Play library is proprietary so I wouldn't like to install it. A gradle flavor that only allows manual location or gps would be easy enough to do but if it were updated less frequently you'd have some version number headaches.

**Comment by dalb8** [comment]
Sound. Bit late, but maybe you are interested: https://github.com/microg/android_packages_apps_UnifiedNlp/issues/36.


-------- Message d'origine --------
De : Kevin Mark <notifications@github.com>
Envoyé: 23 mai 2015 00:57:49 UTC+01:00
À : VersoBit/WeatherDoge <WeatherDoge@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [WeatherDoge] Flavor without GMS (#5)

Closed #5 via c719772d54dfa55d333ae0f3917a94502d7684f8.

---
Reply to this email directly or view it on GitHub:
https://github.com/VersoBit/WeatherDoge/issues/5#event-312153781

**Comment by kmark** [comment]
Thanks, an interesting project. The reason this issue wasn't tackled much earlier was that the gradle build system didn't have the flavor code-merging abilities to cleanly handle the problem. Although now that I look at the AOSP location APIs it seems that the only thing Play services really adds is WiFi geolocation.
